# Generated by Django 5.0.3 on 2024-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serie_alter_movie_genre_alter_movie_uu_id_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
