# Generated by Django 5.0.3 on 2024-04-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_episode_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='movie_views',
        ),
    ]
